//go:build copier

// Copier is a convenience tool that copies the assertions into a project,
// so that they can be used without introducing a direct dependency.
//
// Add the following directive to any .go file and run `go generate ./...`:
//
//	go:generate go run -tags=copier go-simpler.org/assert/cmd/copier@latest <path/to/pkg>
//
// Where <path/to/pkg> is the location where you want to put the generated package,
// e.g. `.` for the project root (hint: for libraries you may want to put it in `internal`).
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"

	"go-simpler.org/assert"
)

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	if err := run(ctx); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func run(ctx context.Context) error {
	if len(os.Args) < 2 {
		return errors.New("path to package is not specified")
	}

	moduleName, err := readModuleName(ctx)
	if err != nil {
		return err
	}

	path := filepath.Join(os.Args[1], "assert")
	fullpath := filepath.Join(path, "EF")

	if err := os.MkdirAll(fullpath, 0755); err != nil && !errors.Is(err, os.ErrExist) {
		return err
	}
	if err := os.Chdir(path); err != nil {
		return err
	}

	importPath := moduleName
	if path != "." {
		importPath = filepath.Join(moduleName, path)
	}

	aliasFile := strings.Replace(assert.AliasFile, "go-simpler.org/assert", importPath, 1)

	if err := writeFile("assert.go", assert.MainFile); err != nil {
		return err
	}
	if err := writeFile("EF/alias.go", aliasFile); err != nil {
		return err
	}

	return nil
}

func readModuleName(ctx context.Context) (string, error) {
	args := [...]string{"go", "mod", "edit", "-json"}

	out, err := exec.CommandContext(ctx, args[0], args[1:]...).Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return "", fmt.Errorf("running %q: %w: %s", strings.Join(args[:], " "), err, string(exitErr.Stderr))
		}
		return "", fmt.Errorf("running %q: %w", strings.Join(args[:], " "), err)
	}

	var info struct {
		Module struct {
			Path string `json:"Path"`
		} `json:"Module"`
	}
	if err := json.Unmarshal(out, &info); err != nil {
		return "", fmt.Errorf("decoding module info: %w", err)
	}

	return info.Module.Path, nil
}

func writeFile(name, content string) error {
	f, err := os.Create(name)
	if err != nil {
		return err
	}
	defer f.Close()

	const header = `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by go-simpler.org/assert/cmd/copier. DO NOT EDIT.

`
	return os.WriteFile(name, []byte(header+content), 0644)
}
