name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  run:
    uses: go-simpler/.github/.github/workflows/lint.yml@reuse-workflows
