name: release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The next semantic version to release

jobs:
  run:
    uses: go-simpler/.github/.github/workflows/release.yml@reuse-workflows
    with:
      version: ${{ github.event_name == 'push' && github.ref_name || inputs.version }}
